spring:
  application.name: broccoli
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE_NAME}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
